name: 'YAPF Python Code Formatting Check'
description: 'Run YAPF to check if your python code is correctly formatted.'
author: "Alexander Melde <alexander@melde.net>"

branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  source-dir:
    description: 'The folder containing the source files to format'
    required: true
    default: './'

runs:
  using: 'composite'
  steps:
    - id: install-yapf
      run: pip install YAPF
      shell: bash
    - id: invoke-yapf
      run: |
        echo "yapf --diff --recursive ${{ inputs.source-dir }} $*"
        yapf --diff --recursive ${{ inputs.source-dir }} $*
      shell: bash
